auto-inspection-url: http://192.168.164.2:8005/par/api/v1/inspection/auto
chrome-driver-path: /kjgk/Project/SeleniumTest/res/chromedriver

auto-inspection-config:
  cwp:
    system-id: 540220231499382784
    url: http://192.168.164.2:8005/cwp
  lhsr:
    system-id: 540106046727782400
    url: http://localhost/lhsr
  lhsrkj:
    system-id: 540220344225497088
    url: https://lhsrkj.com:5443